### ISSUE TITLE
Support JWS JSON Serialization

### ISSUE THREAD

**Issue by lukasjhan** [openwallet-foundation/sd-jwt-js#242]
In [sd-jwt draft 09 section 9](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#name-jws-json-serialization.), JSON Serialization method is added. Let's support this feature in our library

**Comment by lukasjhan** [comment]
There are two kinds of serialization, flatten and general.

I was thinking about adding the converting function between:
- SD-JWT <=> JWS flatten serialization
- SD-JWT <=> JWS general serialization

What do you think about it? @cre8

**Comment by cre8** [comment]
That does not make so much sense:
A generalised Json serialisation can have multiple issuer signatures (required for jades signature). So we can not transfer from this to compact when there are more than one. With flattened it should be possible.

I started the implementation that you pass the issuance function a value what kind of type do you want and the return value is based on this.

Then we need to update the decode function and verify so the three options can be consumed. The default one should be compact to not break any existing implementations

**Comment by lukasjhan** [comment]
Yeah, you're right. A generalised Json serialisation can have multiple signatures. So there is a possibility that it cannot be converted to a compact one.

I think it's better to approach it the way you said. :)

**Comment by cre8** [comment]
I have implemented it for the issuance, but decoding and tests are missing. Maybe I am able to create a pr until Friday

**Comment by lukasjhan** [comment]
To prevent too many changes to the internal implementation, I'm considering creating a new class for JWS JSON-related functions.

**Comment by cre8** [comment]
I don't think that is possible, see my current PR. The jwt object needs to hold multiple signatures, so we need to touch some of the core classes

**Comment by cre8** [comment]
@lukasjhan I think we can close this issue since it was added with your pr, correct?

**Comment by lukasjhan** [comment]
Yes, we can close this.
